name: iOS CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macos-latest

    env:
      SCHEME: instagram-clone
      SDK: iphonesimulator
      DESTINATION: platform=iOS Simulator,name=iPhone 14

    steps:
      # Checkout the code from the repository
      - name: ✅ Checkout code
        uses: actions/checkout@v4

      # Set up Ruby for CocoaPods (necessary for dependencies)
      - name: 🛠 Set up Ruby for CocoaPods
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      # Install xcpretty (to format the build output)
      - name: 📦 Install xcpretty
        run: sudo gem install xcpretty

      # Install CocoaPods dependencies if the Podfile exists
      - name: 📦 Install CocoaPods dependencies
        run: pod install
        if: ${{ hashFiles('Podfile') != '' }}

      # Build the app
      - name: 🧱 Build the app
        run: |
          xcodebuild \
            -scheme "$SCHEME" \
            -sdk "$SDK" \
            -destination "$DESTINATION" \
            -configuration Debug \
            clean build | xcpretty

      # Run tests
      - name: 🧪 Run tests
        run: |
          xcodebuild \
            -scheme "$SCHEME" \
            -sdk "$SDK" \
            -destination "$DESTINATION" \
            test | xcpretty

      # Upload test results (optional)
      - name: 📤 Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: xcode-results
          path: '**/*.xcresult'

