name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest

    env:
      SCHEME: instagram-clone
      SDK: iphonesimulator
      DESTINATION: platform=iOS Simulator,name=iPhone 14

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby (for CocoaPods)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install xcpretty
        run: sudo gem install xcpretty

      - name: Install CocoaPods dependencies (if Podfile exists)
        run: pod install
        if: ${{ always() && hashFiles('Podfile') != '' }}

      - name: Build the app
        run: |
          xcodebuild \
            -scheme "$SCHEME" \
            -sdk "$SDK" \
            -destination "$DESTINATION" \
            -configuration Debug \
            clean build | xcpretty

      - name: Run tests
        run: |
          xcodebuild \
            -scheme "$SCHEME" \
            -sdk "$SDK" \
            -destination "$DESTINATION" \
            test | xcpretty

      - name: Upload test results (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: xcode-results
          path: '*/.xcresult'
